# Secret Scanning Configuration
# These are OAuth Client IDs for a desktop application
# They are intentionally public and required for OAuth flow

paths-ignore:
  - "**/main.ts"
  - "**/cloudServices.ts"
  - "**/*.env.production"
  
# OAuth Client IDs are public by design for desktop apps
# See SECURITY.md for details